export const orders = [
  {
    productId: 1,
    customer: "Liam Jackson",
    date: "12/06/23",
    deliveryType: "express",
    address: "Dhaka",
    phone: "01758142536",
    color: "black",
  },
  {
    productId: 2,
    customer: "Emma Anderson",
    date: "15/06/23",
    deliveryType: "regular",
    address: "New York",
    phone: "1234567890",
    color: "blue",
  },
  {
    productId: 3,
    customer: "Oliver Wilson",
    date: "17/06/23",
    deliveryType: "express",
    address: "London",
    phone: "9876543210",
    color: "red",
  },
  {
    productId: 4,
    customer: "Sophia Martinez",
    date: "20/06/23",
    deliveryType: "regular",
    address: "Los Angeles",
    phone: "5551234567",
    color: "green",
  },
  {
    productId: 5,
    customer: "Noah Johnson",
    date: "22/06/23",
    deliveryType: "express",
    address: "Berlin",
    phone: "0123456789",
    color: "yellow",
  },
  {
    productId: 6,
    customer: "Ava Davis",
    date: "25/06/23",
    deliveryType: "regular",
    address: "Sydney",
    phone: "9876543210",
    color: "purple",
  },
  {
    productId: 7,
    customer: "Mia Thompson",
    date: "28/06/23",
    deliveryType: "express",
    address: "Paris",
    phone: "5551234567",
    color: "orange",
  },
  {
    productId: 8,
    customer: "Jackson Smith",
    date: "01/07/23",
    deliveryType: "regular",
    address: "Tokyo",
    phone: "9876543210",
    color: "pink",
  },
  {
    productId: 9,
    customer: "Isabella Brown",
    date: "04/07/23",
    deliveryType: "express",
    address: "Moscow",
    phone: "5551234567",
    color: "brown",
  },
  {
    productId: 10,
    customer: "Lucas Johnson",
    date: "07/07/23",
    deliveryType: "regular",
    address: "Rio de Janeiro",
    phone: "0123456789",
    color: "gray",
  },
  {
    productId: 11,
    customer: "Sophie Davis",
    date: "10/07/23",
    deliveryType: "express",
    address: "Cairo",
    phone: "9876543210",
    color: "teal",
  },
  {
    productId: 12,
    customer: "Olivia Wilson",
    date: "13/07/23",
    deliveryType: "regular",
    address: "Amsterdam",
    phone: "5551234567",
    color: "maroon",
  },
  {
    productId: 13,
    customer: "Aiden Johnson",
    date: "16/07/23",
    deliveryType: "express",
    address: "Madrid",
    phone: "0123456789",
    color: "silver",
  },
  {
    productId: 14,
    customer: "Scarlett Thompson",
    date: "19/07/23",
    deliveryType: "regular",
    address: "Seoul",
    phone: "9876543210",
    color: "gold",
  },
  {
    productId: 15,
    customer: "Henry Anderson",
    date: "22/07/23",
    deliveryType: "express",
    address: "Mumbai",
    phone: "5551234567",
    color: "navy",
  },
];
